#数据库配置
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/quartz-demo
    username: root
    password: changeme
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: always
      schema: classpath:/db/migrations/V1__init.sql

