spring:
  #数据库配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/quartz-demo
    username: root
    password: changeme
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
  #定时插件配置
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: always
      schema: classpath:/db/migrations/V1__init.sql
  batch:
    initialize-schema: always
